# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='effort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='role',
            field=models.CharField(blank=True, choices=[('p', 'Project Manager'), ('d', 'Developer'), ('t', 'Tester')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Completed'), ('i', 'In Progress'), ('o', 'On Hold'), ('s', 'Started')], max_length=1, null=True),
        ),
    ]
