# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20160907_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='password',
        ),
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Schedule'),
        ),
        migrations.DeleteModel(
            name='MileStone',
        ),
    ]
