# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20160907_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='path',
            field=models.CharField(default=datetime.datetime(2016, 9, 7, 9, 40, 11, 823171, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
