# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20160907_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
    ]
