# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_remove_task_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
