# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20160908_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='selected_row',
            field=models.IntegerField(default=0),
        ),
    ]
