# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_task_end_is_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='task',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='task',
            name='path',
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chart.Task'),
        ),
    ]
