# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20160916_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
